# Generated by Django 2.0.1 on 2018-03-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=6)),
                ('topic', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
