# Generated by Django 2.0.1 on 2018-04-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180419_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classbox',
            name='link',
            field=models.URLField(),
        ),
    ]
