# Generated by Django 2.0.1 on 2018-04-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20180419_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classbox',
            name='class_name',
            field=models.CharField(max_length=8),
        ),
    ]
